services:
  db:
    image: postgres:15-alpine
    ports:
      - "54348:5432"
    environment:
      POSTGRES_DB: mtls-sslcontext-test
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
